# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Reaction Seminar"
description: "Reaction Seminar is a set of seminars in the field of nuclear reactions"
baseurl: "/"
url: "reactionseminar.github.io"
permalink: "/blog/:title"
googleAnalyticsSiteUrl: "reactionseminar.github.io"


# Head
metaKeywords: "Nuclear reaction, Quantum scattering, Fusion"



# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/team/", text: "Team"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://forms.gle/hDzBvVLNmoxA24BJ9", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://forms.gle/hDzBvVLNmoxA24BJ9", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Reaction <typeout> Seminar"
eventDate: "March - May, 2020"
#typeoutTextValues: '"","Scattering", "Fusion","brekup","transfer","knockout","stripping"'
#typeoutFallback: "Scattering"
heroButtons:
 - {link: "https://forms.gle/hDzBvVLNmoxA24BJ9", text: "Become a speaker"}

# About Block
aboutTitle: "About Reaction Seminar"
aboutText1: "For the special time period of COVID-19, we would like to organize a 
series of online seminars that everybody can join. The seminars will cover all fields of nuclear reaction with 
special emphasis on the description and interpretation of different types of direct reactions: elastic/inelastic scattering,
breakup, quasi-free (p,pN) processes, charge-exchange, â€¦ "

aboutText2: "The seminar will be held every XXXday at XX time"

# Partners Block
organizersTitle: "Organizers"


# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates of the schedules"
subscribeAction: "https://github.us19.list-manage.com/subscribe/post?u=1025ea5178e3c2f3a4c0535d6&amp;id=3b24313065"
#subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"


footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:jinlei@pi.infn.it", text: "jinlei@pi.infn.it"}





